const CARDS =  { # Card name, Number, Suit, Ability script, Ability text
	"the_fool" : ["The Fool", 0, "Major", null, null],
	"the_magician" : ["The Magician", 1, "Major", null, null],
	"the_high_priestess" : ["The High Priestess", 2, "Major", null, null],
	"the_empress" : ["The Empress", 3, "Major", null, null],
	"the_emperor" : ["The Emperor", 4, "Major", null, null],
	"the_hierophant" : ["The Hierophant", 5, "Major", null, null],
	"the_lovers" : ["The Lovers", 6, "Major", null, null],
	"the_chariot" : ["The Chariot", 7, "Major", null, null],
	"strength" : ["Strength", 8, "Major", null, null],
	"the_hermit" : ["The Hermit", 9, "Major", null, null],
	"wheel_of_fortune" : ["Wheel of Fortune", 10, "Major", null, null],
	"justice" : ["Justice", 11, "Major", null, null],
	"the_hanged_man" : ["The Hanged Man", 12, "Major", "res://Scripts/Abilities/the_hanged_man.gd", "When played, reverse 1 card in hand."],
	"death" : ["Death", 13, "Major", null, null],
	"temperance" : ["Temperance", 14, "Major", null, null],
	"the_devil" : ["The Devil", 15, "Major", null, null],
	"the_tower" : ["The Tower", 16, "Major", null, null],
	"the_star" : ["The Star", 17, "Major", null, null],
	"the_moon" : ["The Moon", 18, "Major", null, null],
	"the_sun" : ["The Sun", 19, "Major", null, null],
	"judgement" : ["Judgement", 20, "Major", null, null],
	"the_world" : ["The World", 21, "Major", null, null]
}
